spring:
  application:
    name: @project.artifactId@
  config:
    import: "optional:configtree:/secrets/"

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug
