{{- if not .Values.externalDatabase.existingConfiguration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meals-advisor.backend.name" . }}-config
data:
  application.properties: |
    {{- with .Values.externalDatabase }}
    spring.datasource.url=jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .database }}?currentSchema={{ .schema }}
    spring.datasource.username={{ .username }}
    spring.jpa.hibernate.ddl-auto=update
    {{- end }}
{{- end }}
