{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meals-advisor.backend.name" . }}-secret
type: Opaque
data:
  spring.datasource.password: {{ .Values.externalDatabase.password | default (randAlphaNum 10) | b64enc | quote }}
{{- end }}
